use_frameworks!

platform :ios, '10.0'

target 'STIMSDKIOS_Example' do
  pod 'STIMSDKIOS', :path => '../'

  target 'STIMSDKIOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
