use_frameworks!

platform :ios, '10.0'

target 'STIMSDKIOS_Example' do
    use_modular_headers!
  pod 'STIMSDKIOS', :path => '../'
  pod 'QMUIKit'
  pod 'SVProgressHUD'
  target 'STIMSDKIOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
